# Generated by Django 4.1.7 on 2023-04-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_webiste',
            new_name='social_website',
        ),
    ]
