# Generated by Django 4.1.7 on 2023-04-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
