# Generated by Django 4.1.7 on 2023-04-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='profile_image',
            new_name='featured_image',
        ),
    ]
